Description: Open OnDemand on AWS Full Deployment (Infrastructure + OOD)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Portal
        Parameters:
          - WebsiteDomainName
          - PortalAllowedIPCIDR
      - Label:
          default: Route53
        Parameters:
          - HostedZoneId
      - Label:
          default: Active Directory
        Parameters:
          - TopLevelDomain
          - DomainName
      - Label:
          default: Open OnDemand
        Parameters:
          - Branch
          - SlurmVersion          
    ParameterLabels:
      PortalAllowedIPCIDR:
        default: Portal Allowed IP CIDR
      WebsiteDomainName:
        default: Website Domain Name
      HostedZoneId:
        default: Hosted Zone Id
Parameters:
  DomainName:
    Description: Domain name not including the top level domain
    Default: hpclab
    Type: String
    AllowedPattern: '[a-zA-Z0-9]+'
  TopLevelDomain:
    Description: TLD for your domain (i.e. local, com, etc)
    Type: String
    MinLength: '1'
    MaxLength: '15'
    Default: local
    AllowedPattern: '[a-zA-Z0-9]+'
  WebsiteDomainName:
    Description: Domain name for world facing website
    Type: String
  HostedZoneId:
    Description: Hosted Zone Id for Route53 Domain
    Type: String
  PortalAllowedIPCIDR:
    Description: IP CIDR for access to the Portal
    Type: String
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  Branch:
    Description: Branch of the code to deploy. Only use this when testing changes to the solution
    Default: main
    Type: String
  SlurmVersion:
    Description: Verion of slurm to install
    Default: 23.11.7
    Type: String
  DeploymentAssetBucketName:
    Description: Deployment Asset Bucket Name
    Type: String
    Default: ood-assets

Resources:
  OODInfra:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DomainName: !Ref DomainName
        TopLevelDomain: !Ref TopLevelDomain
      TemplateURL: !Sub https://${DeploymentAssetBucketName}.s3.amazonaws.com/assets/cloudformation/infra.yml

  OOD:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPC: !GetAtt [ OODInfra, Outputs.VPCId ]
        PublicSubnets: !GetAtt [ OODInfra, Outputs.PublicSubnets ]
        PrivateSubnets: !GetAtt [ OODInfra, Outputs.PrivateSubnets ]
        DomainName: !GetAtt [ OODInfra, Outputs.DomainName ]
        TopLevelDomain: !GetAtt [ OODInfra, Outputs.TopLevelDomain ]
        HostedZoneId: !Ref HostedZoneId
        PortalAllowedIPCIDR: !Ref PortalAllowedIPCIDR
        WebsiteDomainName: !Ref WebsiteDomainName
        ADAdministratorSecret: !GetAtt [ OODInfra, Outputs.ADAdministratorSecretARN ]
        LDAPNLBEndPoint: !GetAtt [ OODInfra, Outputs.LDAPNLBEndPoint ]
        LoadBalancerLogBucket: !GetAtt [ OODInfra, Outputs.LoadBalancerLogBucket ]
        Branch: !Ref Branch
        SlurmVersion: !Ref SlurmVersion
      TemplateURL: !Sub https://${DeploymentAssetBucketName}.s3.amazonaws.com/assets/cloudformation/ood.yml

Outputs:
  PrivateSubnets:
    Value: !GetAtt OODInfra.Outputs.PrivateSubnets
    Description: Private Subnets
  URL:
    Description: URL
    Value: !GetAtt OOD.Outputs.URL
  ClusterConfigBucket:
    Description: S3 Bucket where Cluster Configuration items are stored
    Value: !GetAtt OOD.Outputs.ClusterConfigBucket
  SecretId:
    Description: Open OnDemand Secret ID
    Value: !GetAtt OOD.Outputs.SecretId
  DBSecretId:
    Description: DB Secret ARN
    Value: !GetAtt OOD.Outputs.DBSecretId
  MungeKeySecretId:
    Description: Munge Key Secret ARN
    Value: !GetAtt OOD.Outputs.MungeKeySecretId
  EFSMountId:
    Description: EFS Mount ID
    Value: !GetAtt OOD.Outputs.EFSMountId
  HeadNodeIAMPolicyArn:
    Description: Parallel Cluster Head Node IAM ARN
    Value: !GetAtt OOD.Outputs.HeadNodeIAMPolicyArn
  ComputeNodeIAMPolicyArn:
    Description: Parallel Cluster Head Node IAM ARN
    Value: !GetAtt OOD.Outputs.ComputeNodeIAMPolicyArn
  HeadNodeSecurityGroup:
    Description: Additional Security Group for Parallel Cluster Head Nodes
    Value: !GetAtt OOD.Outputs.HeadNodeSecurityGroup
  ComputeNodeSecurityGroup:
    Description: Additional Security Group for Parallel Cluster Compute Nodes
    Value: !GetAtt OOD.Outputs.ComputeNodeSecurityGroup
  ADAdministratorSecretARN:
    Description: AD Admin Secret ARN
    Value: !GetAtt OODInfra.Outputs.ADAdministratorSecretARN
  LDAPNLBEndPoint:
    Description: LDAP NLB End Point
    Value: !GetAtt OODInfra.Outputs.LDAPNLBEndPoint
